[default]
LOG_LEVEL = "INFO"
USE_OPENTELEMETRY = true

[default.opentel]
OTEL_ENDPOINT = "http://localhost:4317"
SERVICE_NAME = "LLM_Prompt_Transpiler"
SERVICE_VERSION = "1.0.0"

[default.openai]
DEFAULT_OPENAI_BASIC_MODEL = "gpt-4o-mini"
DEFAULT_OPENAI_THINKING_MODEL = "gpt-4o"
TEMPERATURE = 0.0
